/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// This file defines MERN schema definitions or TypeScript modeling structures for student reference.
// Ideal as a classroom study resource or GitHub proof-of-work detailing schema layouts.

export interface UserSchema {
  id: string; // crypto.randomUUID()
  email: string;
  name?: string;
  currency: string; // Base currency: e.g. INR, USD, EUR
  passwordHash: string;
  createdAt: string;
}

export interface CategorySchema {
  id: string;
  name: string;
  type: 'INCOME' | 'EXPENSE';
  icon: string; // Lucide icon alias
  userId: string; // 'system' or custom authenticated id
}

export interface TransactionSchema {
  id: string;
  userId: string;
  amount: number; // Raw amount logged
  currency: string; // Currency selected (e.g., INR)
  amountBase: number; // Converted equivalent in base currency
  description: string;
  categoryId: string;
  categoryName?: string;
  categoryType?: 'INCOME' | 'EXPENSE';
  date: string; // ISO Split YYYY-MM-DD
  source: 'manual' | 'csv' | 'ocr';
  recurringRuleId?: string; // Flagged if generated by repeating cron
  scannedReceiptImg?: string; // Base64 visual backup stub
}

export interface BudgetSchema {
  id: string;
  userId: string;
  categoryId: string | null; // Null stands for global monthly limit limits
  categoryName?: string;
  period: 'monthly' | 'weekly';
  amount: number;
  currency: string;
  startOn: string;
}

export interface RecurringRuleSchema {
  id: string;
  userId: string;
  amount: number;
  currency: string;
  categoryId: string | null;
  categoryName?: string;
  description: string;
  period: 'monthly' | 'weekly';
  nextRun: string; // Evaluated state run date
  active: boolean; // Flag if system cron can trigger jobs
}
